name: CI

on:
  push:
    branches: 
      - master

jobs:
  build-linux:
    runs-on: ubuntu-16.04
    steps:
    - name: Install Dependencies
      run: |
        sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial
        sudo apt-get update -qq
        sudo apt-get install qt512-meta-minimal qt512x11extras qt512tools qt512translations qt512svg qt512multimedia qt512gamepad libgl1-mesa-dev
    - name: Build and install the-libs
      run: |
        source /opt/qt512/bin/qt512-env.sh || true
        git clone https://github.com/vicr123/the-libs.git
        cd the-libs
        git checkout blueprint
        qmake
        make
        sudo make install INSTALL_ROOT=/
    - name: Build libentertaining
      run: |
        source /opt/qt512/bin/qt512-env.sh || true
        git clone https://github.com/vicr123/libentertaining.git
        cd libentertaining
        qmake
        make
        sudo make install INSTALL_ROOT=/
    - name: Build Contemporary
      run: |
        source /opt/qt512/bin/qt512-env.sh || true
        git clone https://github.com/vicr123/contemporary-theme.git
        cd contemporary-theme
        qmake
        make
        sudo make install INSTALL_ROOT=/
        cd ..
    - uses: actions/checkout@v1
    - name: Build Entertaining Mines
      run: |
        source /opt/qt512/bin/qt512-env.sh || true
        qmake
        make
        make install INSTALL_ROOT=~/appdir
    - name: Create AppImage
      run: |
        source /opt/qt512/bin/qt512-env.sh || true
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage ~/appdir/usr/share/applications/*.desktop -appimage -extra-plugins=iconengines/libqsvgicon.so,imageformats/libqsvg.so,styles/libContemporary.so
    - name: Prepare AppImage
      run: |
        cp Entertaining_Mines*.AppImage entertaining-mines-linux.AppImage
    - name: Deploy AppImage
      run: |
        export RELEASE_NAME="continuous"
        export RELEASE_TITLE="Continuous build"
        export is_prerelease="true"
        export REPO_SLUG=$GITHUB_REPOSITORY
        export TRAVIS_BRANCH="master"
        export TRAVIS_COMMIT=$GITHUB_SHA
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh entertaining-mines-linux.AppImage*
