name: CI

on:
  push:
    branches: 
      - master

jobs:
  build-linux:
    runs-on: ubuntu-16.04
    steps:
    - uses: vicr123/the-libs/bootstrap@actions
      with:
        extra-deps-linux: "qt512gamepad"
    - name: Build libentertaining
      run: |
        source /opt/qt512/bin/qt512-env.sh || true
        git clone https://github.com/vicr123/libentertaining.git
        cd libentertaining
        qmake
        make
        sudo make install INSTALL_ROOT=/
    - name: Build Contemporary
      run: |
        source /opt/qt512/bin/qt512-env.sh || true
        git clone https://github.com/vicr123/contemporary-theme.git
        cd contemporary-theme
        qmake
        make
        sudo make install INSTALL_ROOT=/
        cd ..
    - uses: actions/checkout@v1
    - uses: vicr123/the-libs/build@actions
    - uses: vicr123/the-libs/image@actions
      id: image
      with:
        extra-plugins-linux: "styles/libContemporary.so"
        image-name-linux: entertaining-mines-linux.AppImage
    - name: Deploy AppImage
      run: |
        export RELEASE_NAME="continuous"
        export RELEASE_TITLE="Continuous build"
        export is_prerelease="true"
        export REPO_SLUG=$GITHUB_REPOSITORY
        export TRAVIS_BRANCH="master"
        export TRAVIS_COMMIT=$GITHUB_SHA
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh ${{ steps.image.outputs.image-path }}
