name: CI

on:
  push:
    branches: 
      - master

jobs:
  build-linux:
    runs-on: ubuntu-16.04
    steps:
    - uses: vicr123/the-libs/bootstrap@actions
      name: "Bootstrap Build"
      with:
        extra-deps-linux: "qt512gamepad"
    - uses: vicr123/libentertaining/actions/build@master
      name: Build libentertaining
    - uses: vicr123/contemporary-theme/actions/build@master
      name: Build Contemporary
    - uses: actions/checkout@v1
    - uses: vicr123/the-libs/build@actions
      name: "Build Project"
    - uses: vicr123/the-libs/image@actions
      name: "Package Project"
      id: image
      with:
        extra-plugins-linux: "styles/libContemporary.so"
        image-name-linux: entertaining-mines-linux.AppImage
    - name: Deploy Project
      run: |
        export RELEASE_NAME="continuous"
        export RELEASE_TITLE="Continuous build"
        export is_prerelease="true"
        export REPO_SLUG=$GITHUB_REPOSITORY
        export TRAVIS_BRANCH="master"
        export TRAVIS_COMMIT=$GITHUB_SHA
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh ${{ steps.image.outputs.image-path }}
